### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by voldikss** [voldikss/coc-translator#8]
- [x] 多引擎查询，个别查询引擎网络超时解决
- [x] Syntax hightlight
- [x] Visual mode keymap
- [x] Multithreading like query?
- [ ] Local dictionary?
- [ ] Youdao api: [Ref1](https://github.com/chinanf-boy/translationjs-fix/blob/master/src/api/youdao/web/index.ts) -> [Ref2](https://github.com/voldikss/coc-translator/blob/master/src/commands/translator.ts#L145)
- [x] CocCommand translator.popup [word]?

**Comment by voldikss** [comment]
Solution for multithreading for multi-engine query:

```typescript
// engines
for (const e of engines){
SetTimeout(e.translation(...))
}

// popup:
if (there is already a popup window) // use this.windows.length....
{
    setConfig....// expand window
    // append the new translation
}
else {
    // create a new window
    // append the new translation
}
```
